services:
  traefik:
    image: traefik:v2.10
    command:
      - "--api.dashboard=true" # Enable Traefik dashboard (optional, secure in production)
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80" # HTTP entrypoint
      - "--entrypoints.websecure.address=:443" # HTTPS entrypoint
      - "--certificatesresolvers.le.acme.httpchallenge=true"
      - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.le.acme.email=${LETS_ENCRYPT_EMAIL}" # Replace with your email
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80" # Expose HTTP
      - "443:443" # Expose HTTPS
      - "8080:8080" # Traefik dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro" # Allow Traefik to listen to Docker events
      - "./letsencrypt:/letsencrypt" # Store SSL certificates
    restart: always

  cantaloupe:
    image: islandora/cantaloupe:2.0.10
    environment:
      CANTALOUPE_SOURCE_STATIC: AzureStorageSource
      CANTALOUPE_AZURESTORAGESOURCE_ACCOUNT_NAME: ${CANTALOUPE_AZURESTORAGESOURCE_ACCOUNT_NAME}
      CANTALOUPE_AZURESTORAGESOURCE_ACCOUNT_KEY: ${CANTALOUPE_AZURESTORAGESOURCE_ACCOUNT_KEY}
      CANTALOUPE_AZURESTORAGESOURCE_CONTAINER_NAME: ${CANTALOUPE_AZURESTORAGESOURCE_CONTAINER_NAME}
      CANTALOUPE_AZURESTORAGESOURCE_PATH_PREFIX: /
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cantaloupe.rule=Host(`${CANTALOUPE_HOST}`)" # Host from environment variable
      - "traefik.http.routers.cantaloupe.entrypoints=websecure"
      - "traefik.http.routers.cantaloupe.tls=true"
      - "traefik.http.routers.cantaloupe.tls.certresolver=le"
      - "traefik.http.services.cantaloupe.loadbalancer.server.port=8182"
    restart: always